//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KindOfItem.h
//  @ Date : 24.07.2024
//  @ Author : 
//
//


#if !defined(_KINDOFITEM_H)
#define _KINDOFITEM_H


enum KindOfItem {
	Sword,
	HealingPotion,
	Axe,
	PotionOfHealth,
	LeatherArmor,
	IronArmor,
    LeatherHelmet,
    IronHelmet
};

#endif  //_KINDOFITEM_H
