//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MonsterRace.h
//  @ Date : 24.07.2024
//  @ Author : 
//
//


#if !defined(_MONSTERRACE_H)
#define _MONSTERRACE_H


enum MonsterRace {
	Ork,
	Goblin,
	Demon,
	Kobold
};

#endif  //_MONSTERRACE_H
