//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.h
//  @ Date : 24.07.2024
//  @ Author : 
//
//


#if !defined(_PLAYER_H)
#define _PLAYER_H

#include "Entity.h"
#include "Item.h"
#include <string>

class Player : public Entity {
public:
	std::string nickname;
    unsigned int monstersKilled = 0;
    unsigned int numberOfKilledKobolds = 0;
    unsigned int numberOfKilledGoblin = 0;
    unsigned int numberOfKilledDemons = 0;
    unsigned int numberOfKilledOrks = 0;
    unsigned int numberOfSpendCoins = 0;
    unsigned int numberOfTakenDamage = 0;
    unsigned int numberOfMadeDamage = 0;
    Player(std::string nickname);
};

#endif  //_PLAYER_H
