//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.cpp
//  @ Date : 24.07.2024
//  @ Author : 
//
//


#include "Player.h"
#include "Item.h"
#include <cstdlib>
#include <ctime>

Player::Player(std::string nickname){
    this->nickname = nickname;
    this->maxHitPoints = 100;
    this->currentHitPoints = 100;
    this->numberOfCoins = 0;
    srand(time(0));
    this->atackPower = rand() % 10 + 10;
}

